### ISSUE TITLE
Actividad 3

### ISSUE THREAD

**Issue by SandyMarissaGs** [SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-SandyMarissaGs#1]
[CUADRO COMPARATIVO DEL METODO CIENTIFICO F.I..pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-SandyMarissaGs/files/9466300/CUADRO.COMPARATIVO.DEL.METODO.CIENTIFICO.F.I.pdf)
Grupo 1BS.
Sandy Marissa García Santiago.
Actividad 3

**Comment by YaelTrinidad** [comment]
ACTIVIDAD 3 CUADRO COMPARATIVO
DE 20% DE LA ACTIVIDAD OBTUVISTE 11.6 % DE ACUERDO A LA RUBRICA

**Comment by josealfredo79** [comment]
Revisado...
